from screeninfo import get_monitors
from math import  sqrt

MAP_SIZE_PERCENTS = 133
SQUARE_WIDTH_METER = 220

MONITOR_WIDTH_PIXEL = 1920
MONITOR_HEIGHT_PIXEL = 1200
SQUARE_WIDTH_PIXEL = 68
SQUARE_HEIGHT_PIXEL = 68
MAP_WIDTH_PIXELS = 480
MAP_HEIGHT_PIXELS = 480

WIDTH_PIXELS_PER_METER = MONITOR_WIDTH_PIXEL / SQUARE_WIDTH_METER
HEIGHT_PIXELS_PER_METER = MONITOR_HEIGHT_PIXEL / SQUARE_WIDTH_METER






# point_a = (223, 104)
# point_b = (475, 96)
# DISTANCE_PIXELS = sqrt((point_b[0] - point_a[0]) ** 2 + (point_b[1] - point_a[1]) ** 2)
# DISTANCE_METERS =  DISTANCE_PIXELS / PIXELS_PER_METER
# print(DISTANCE_METERS)